<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>si.result.lib</groupId>
    <artifactId>spring-boot-service</artifactId>
    <version>1.1.1-SNAPSHOT</version>
  </parent>
  <groupId>si.result.eearly</groupId>
  <artifactId>eearly-admin</artifactId>
  <version>0.11.4-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>eearly-admin</name>

  <ciManagement>
    <system>GitLab,Jenkins,Nexus,SonarQube</system>
    <notifiers>
      <notifier>
        <type>slack</type>
        <address>eearly-admin</address>
        <sendOnError>true</sendOnError>
        <sendOnFailure>true</sendOnFailure>
        <sendOnSuccess>true</sendOnSuccess>
      </notifier>
      <notifier>
        <type>gitlab-merge-request-comment</type>
        <sendOnError>true</sendOnError>
        <sendOnFailure>true</sendOnFailure>
        <sendOnSuccess>true</sendOnSuccess>
      </notifier>
    </notifiers>
  </ciManagement>

  <repositories>
    <repository>
      <id>result-lib</id>
      <name>Result Lib</name>
      <url>https://nexus.result.si/repository/result-lib/</url>
      <snapshots>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </repository>
  </repositories>

  <distributionManagement>
    <repository>
      <id>e-early-backend-release</id>
      <name>eEarly Backend Release</name>
      <url>https://nexus.result.si/repository/eearly-backend-release/</url>
    </repository>
    <snapshotRepository>
      <id>e-early-backend-snapshot</id>
      <name>eEarly Backend Snapshot</name>
      <url>https://nexus.result.si/repository/eearly-backend-snapshot/</url>
    </snapshotRepository>
  </distributionManagement>

  <profiles>
    <profile>
      <id>development</id>
      <properties>
        <spring.profiles.active>development</spring.profiles.active>
      </properties>
    </profile>
    <profile>
      <id>public</id>
      <properties>
        <spring.profiles.active>public</spring.profiles.active>
      </properties>
    </profile>
    <profile>
      <id>unrestricted</id>
      <properties>
        <spring.profiles.active>unrestricted</spring.profiles.active>
      </properties>
    </profile>
  </profiles>
  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>si.result.lib</groupId>
        <artifactId>spring-boot-service</artifactId>
        <version>1.1.1-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Modules -->
      <dependency>
        <groupId>si.result.eearly</groupId>
        <artifactId>eearly-admin-domain</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>si.result.eearly</groupId>
        <artifactId>eearly-admin-rest-adapter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>si.result.eearly</groupId>
        <artifactId>eearly-admin-persistence-adapter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>si.result.eearly</groupId>
        <artifactId>eearly-admin-grpc-adapter</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.amashchenko.maven.plugin</groupId>
        <artifactId>gitflow-maven-plugin</artifactId>
        <version>1.21.0</version>
        <configuration>
          <allowSnapshots>true</allowSnapshots>
          <pushRemote>true</pushRemote>
          <gitFlowConfig>
            <productionBranch>master</productionBranch>
            <developmentBranch>development</developmentBranch>
            <featureBranchPrefix>feature/</featureBranchPrefix>
            <releaseBranchPrefix>release/</releaseBranchPrefix>
            <hotfixBranchPrefix>hotfix/</hotfixBranchPrefix>
          </gitFlowConfig>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <modules>
    <module>eearly-admin-service</module>
    <module>eearly-admin-domain</module>
    <module>eearly-admin-rest-adapter</module>
    <module>eearly-admin-persistence-adapter</module>
    <module>eearly-admin-grpc-adapter</module>
  </modules>
</project>
